---
openapi: 3.0.3
info:
  title: "WebAPI for JRS, OPI and WSV exercises"
  version: "0.1"
paths:
  /api/opi/touchpoints:
    get:
      operationId: readAllTouchpoints
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StationaryTouchpoint'
    post:
      operationId: createTouchpoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StationaryTouchpoint'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationaryTouchpoint'
  /api/opi/touchpoints/{id}:
    get:
      operationId: readTouchpoint
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationaryTouchpoint'
    delete:
      operationId: deleteTouchpoint
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: boolean
  /api/touchpoints:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StationaryTouchpoint'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StationaryTouchpoint'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationaryTouchpoint'
  /api/touchpoints/{touchpointId}:
    get:
      parameters:
      - name: touchpointId
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationaryTouchpoint'
    delete:
      parameters:
      - name: touchpointId
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: boolean
components:
  schemas:
    AbstractTouchpoint:
      type: object
      properties:
        id:
          format: int64
          type: integer
        erpPointOfSaleId:
          format: int64
          type: integer
        name:
          type: string
    Address:
      type: object
      properties:
        id:
          format: int64
          type: integer
        geoLat:
          format: int64
          type: integer
        geoLong:
          format: int64
          type: integer
        street:
          type: string
        houseNr:
          type: string
        zipCode:
          type: string
        city:
          type: string
    StationaryTouchpoint:
      type: object
      properties:
        id:
          format: int64
          type: integer
        erpPointOfSaleId:
          format: int64
          type: integer
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
